version: 0.2

env:
  variables:
    SNS_TOPIC_ARN: "arn:aws:sns:ap-south-1:243599567017:JenkinsNotification"

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Processing AccountId: ${ACCOUNT_ID}"
      - |
        aws sns publish \
          --region ap-south-1 \
          --topic-arn "$SNS_TOPIC_ARN" \
          --message "{\"AccountId\":\"${ACCOUNT_ID}\", \"Status\": true}"
